//! A block: one submitted command together with its captured output and exit
//! code. The atomic unit of the transcript and the foundation for later
//! features (D8). See `data-model.md` for the full entity description.

use std::ops::Range;
use std::path::PathBuf;
use std::time::{Duration, SystemTime};

use wezterm_term::StableRowIndex;

use crate::session::ringbuf::OutputBuffer;

/// Monotonically increasing block identifier, unique within a session.
pub type BlockId = u64;

/// The DB-ready text accessor seam (FR-019/020, SC-010). Callers (`/save`,
/// `/filter`, render) obtain a block's text **only** through this trait, so a
/// future persistent backing can implement it without reshaping callers.
///
/// Both accessors return owned `String`: the retained output lives in a
/// non-contiguous ring buffer ([`OutputBuffer`]) decoded lazily on access, so a
/// borrowed `&str` would require `&mut`. Owned text also suits every caller
/// (write to file, filter, copy) without further allocation churn.
pub trait BlockText {
    /// The block's captured output text only.
    fn text(&self) -> String;
    /// The command line followed by a newline and the output text.
    fn text_with_command(&self) -> String;
}

/// Lifecycle state of a block.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BlockState {
    /// The command is running and output is being captured.
    Running,
    /// The command has finished; the block is closed.
    Closed,
    /// The command entered an alt-screen program; capture is suspended.
    Interactive,
}

/// One command plus its captured output and exit code.
#[derive(Debug)]
pub struct Block {
    pub id: BlockId,
    pub command: String,
    /// Wall-clock at command execution (OSC 133 `C`, sentinel fallback);
    /// `None` until the command actually starts running. Serializable for a
    /// future DB backing (FR-029).
    pub started_at: Option<SystemTime>,
    /// Wall-clock at command end (OSC 133 `D`); `None` until sealed.
    pub ended_at: Option<SystemTime>,
    pub output: OutputBuffer,
    pub exit_code: Option<i32>,
    pub state: BlockState,
    /// Grid rows this block's output occupies, anchored to `StableRowIndex` so
    /// the range survives scrollback eviction (block-as-annotation, FR-018).
    pub row_range: Range<StableRowIndex>,
    /// Working directory captured from OSC 7, if known.
    pub cwd: Option<PathBuf>,
    /// `false` once all referenced grid rows are evicted and only the retained
    /// `output` text remains; callers surface this as "unavailable" (FR-025).
    pub available: bool,
    /// Reserved for the post-MVP privacy feature (D13); always `false` in MVP.
    pub private: bool,
    /// Reserved for the post-MVP output-retention feature (D13); `true` in MVP.
    pub save_output: bool,
    /// `true` when this block was generated by kapollo itself (e.g. `/help`)
    /// rather than typed by the user, so the UI and `/save`/`/filter` can tell
    /// synthetic output from real shell commands (D25).
    pub synthetic: bool,
}

impl Block {
    /// Create a new `Running` block for `command`, with an output buffer bound
    /// by the given caps.
    pub fn new(id: BlockId, command: String, cap_bytes: u64, cap_lines: u64) -> Self {
        Self {
            id,
            command,
            started_at: None,
            ended_at: None,
            output: OutputBuffer::new(cap_bytes, cap_lines),
            exit_code: None,
            state: BlockState::Running,
            row_range: 0..0,
            cwd: None,
            available: true,
            private: false,
            save_output: true,
            synthetic: false,
        }
    }

    /// Append captured output bytes to this block.
    pub fn push_output(&mut self, data: &[u8]) {
        self.output.push(data);
    }

    /// Close the block, recording its end time and exit code.
    pub fn close(&mut self, exit_code: Option<i32>) {
        self.ended_at = Some(SystemTime::now());
        self.exit_code = exit_code;
        self.state = BlockState::Closed;
    }

    /// Elapsed command runtime: `ended_at − started_at`. `None` until both the
    /// start (OSC 133 `C`) and end (OSC 133 `D`) timestamps are recorded
    /// (FR-029, data-model "Block").
    pub fn duration(&self) -> Option<Duration> {
        match (self.started_at, self.ended_at) {
            (Some(start), Some(end)) => end.duration_since(start).ok(),
            _ => None,
        }
    }

    /// Whether this block's output was truncated to honor a cap.
    pub fn truncated(&self) -> bool {
        self.output.truncated()
    }

    /// The captured output decoded lossily as UTF-8 for rendering.
    pub fn output_lossy(&self) -> String {
        String::from_utf8_lossy(&self.output.to_vec()).into_owned()
    }
}

impl BlockText for Block {
    fn text(&self) -> String {
        self.output_lossy()
    }

    fn text_with_command(&self) -> String {
        format!("{}\n{}", self.command, self.output_lossy())
    }
}
